# Generated by Django 5.1.2 on 2024-10-28 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=255, unique=True)),
                ('agent_name', models.CharField(max_length=255)),
                ('model_type', models.CharField(max_length=255)),
                ('llm_websocket_url', models.URLField()),
                ('llm_id', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('beginMessage', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=50, unique=True)),
                ('agent_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('call_type', models.CharField(max_length=50)),
                ('call_summary', models.TextField(blank=True, null=True)),
                ('call_recording_url', models.URLField(blank=True, null=True)),
                ('start_timestamp', models.BigIntegerField()),
                ('end_timestamp', models.BigIntegerField()),
                ('duration_ms', models.IntegerField()),
                ('transcript', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=255, unique=True)),
                ('voice_type', models.CharField(max_length=255)),
                ('voice_name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('accent', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar_url', models.URLField()),
                ('preview_audio_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('inbound_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_calls', to='Tax_app.agent')),
                ('outbound_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_calls', to='Tax_app.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='voice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tax_app.voice'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
